name: ci-small-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  small-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Sanity check
        run: |
          echo "CI triggered for $GITHUB_REPOSITORY @ $GITHUB_SHA"
          echo "Runner: $(uname -a)"
          echo "CI is working."

