# Generated by Django 5.2.5 on 2025-08-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='authentification_customuser',
        ),
    ]
